### PR TITLE
Add the disassembler

### PR DESCRIPTION
**Pull request by pitust**
This adds the disassembler.

Signed-off-by: pitust <piotr@stelmaszek.com>

### CODE REVIEW

**Comment by pitust** [comment]
A sample of what it produces: ```assembly
<module>:
	129
	str LightMatrix
	tuple 1
	import.nm lightmatrix
	import.from LightMatrix
	st.name LightMatrix
	pop
	129
	str Button
	tuple 1
	import.nm button
	import.from Button
	st.name Button
	pop
	129
	str StatusLight
	tuple 1
	import.nm statuslight
	import.from StatusLight
	st.name StatusLight
	pop
	129
```

**Comment by pitust** [comment]
It does seem to be a bit buggy though.

**Comment by pitust** [comment]
Is there any reason to not merge it now?

**Comment by gpdaniels** [comment]
I'm hesitant to add the entire micropython repo as a submodule. 
If it only depends on the `mpy-tool.py` it'd probably be better to just copy that file over.

**Comment by pitust** [comment]
Unfortunatly, micropython's tools are really tightly interconnected. I will write a batch script to do (2) though.

**Comment by gpdaniels** [comment]
Playing with this, you can extract the `mpy-tool.py` you just need the `makeqstrdata.py` file too.

**Comment by pitust** [comment]
Great! i will refactor it and push it all soon.

**Comment by pitust** [comment]
^ Yeah, i am done refactoring this

**Comment by gpdaniels** [comment]
Can you also remove the generated files, as they'll change with each release, and with improvements to the decompiler.

**Comment by pitust** [comment]
Sure! They are actually already out of date, since the decompiler got a lot of changes over the last two hours.

**Comment by gpdaniels** [comment]
Looking good!
I've been attempting to port it across to python too for my convenience, so will make sure to add any changes.
I think the micropython submodule is still here?

**Comment by pitust** [comment]
I don't think so. I removed it in eeb94d1

**Comment by pitust** [comment]
Actually, i removed it in 778292, because i didn't remove the submodule properly

**Comment by pitust** [comment]
Wait, i am going to push my latest disassembler

**Comment by pitust** [comment]
here, my latest disassembler is up

**Pull request merged**
